<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../AnoMech/Core/Combat/CombatTiming.cs" />
    <Compile Include="../AnoMech/Core/Map/StartLocationRules.cs" />
    <Compile Include="../AnoMech/Core/Map/MapController.cs" />
    <Compile Include="../AnoMech/Core/Map/TargetInstance.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P2PartySynergy/*Ai.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P2PartySynergy/*State*.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P3Monitors/TopP3MonitorRules.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P5Delta/*Ai.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P5Sigma/*MoogleAi.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P5Omega/*Ai.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P5Omega/*State*.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P4BlueScreen/TopP4BlueScreenRules.cs" Link="Production/TopP4BlueScreenRules.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P4BlueScreen/TopP4BlueScreenState.cs" Link="Production/TopP4BlueScreenState.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P4BlueScreen/TopP4BlueScreenAi.cs" Link="Production/TopP4BlueScreenAi.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P4BlueScreen/TopP4BlueScreenMechanics.cs" Link="Production/TopP4BlueScreenMechanics.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P5Delta/TopP5DeltaState.cs" Link="Production/TopP5DeltaState.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P5Delta/TopP5DeltaStateOverrides.cs" Link="Production/TopP5DeltaStateOverrides.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P5Delta/TopP5DeltaSettingsWindow.cs" Link="Production/TopP5DeltaSettingsWindow.cs" />
    <Compile Include="../AnoMech/Core/Game/Placement.cs" Link="Production/Placement.cs" />
    <Compile Include="../AnoMech/Core/SimObjects/IPositioned.cs" Link="Production/IPositioned.cs" />
    <Compile Include="../AnoMech/Helpers/ShuffleExtensions.cs" Link="Production/ShuffleExtensions.cs" />
    <Compile Include="../AnoMech/Scenarios/RoleList.cs" Link="Production/RoleList.cs" />
    <Compile Include="../AnoMech/Scenarios/Rng.cs" Link="Production/Rng.cs" />
    <Compile Include="../AnoMech/Scenarios/ScenarioStates.cs" Link="Production/ScenarioStates.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/MarkerMode.cs" Link="Production/MarkerMode.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P5Sigma/TopP5SigmaAi.cs" Link="Production/TopP5SigmaAi.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P5Sigma/TopP5SigmaTuuuflessAi.cs" Link="Production/TopP5SigmaTuuuflessAi.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P5Sigma/TopP5SigmaState.cs" Link="Production/TopP5SigmaState.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P5Sigma/TopP5SigmaStateOverrides.cs" Link="Production/TopP5SigmaStateOverrides.cs" />
    <Compile Include="../AnoMech/Core/Game/Ai/*.cs" Link="Production/%(Filename)%(Extension)" />
    <Compile Include="../AnoMech/Core/Game/EventScheduler.cs" Link="Production/EventScheduler.cs" />
    <Compile Include="../AnoMech/Core/Game/Party/PartyRole.cs" Link="Production/PartyRole.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/TopConstants.cs" Link="Production/TopConstants.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P3HelloWorld/TopP3HelloWorldAi.cs" Link="Production/TopP3HelloWorldAi.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P3HelloWorld/TopP3HelloWorldMechanics.cs" Link="Production/TopP3HelloWorldMechanics.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P3HelloWorld/TopP3TransitionRules.cs" Link="Production/TopP3TransitionRules.cs" />
    <Compile Include="../AnoMech/Scenarios/Top/P3HelloWorld/TopP3Transition.cs" Link="Production/TopP3Transition.cs" />
  </ItemGroup>
</Project>
