PartyListOrderChecks.Run();
CrossMonitorChecks.Run();
if (args.Contains("--combat-recast-only")) { CombatRecastChecks.Run(); return; }
CombatRecastChecks.Run();
CombatTimingChecks.Run();
WarriorCombatChecks.Run();
JobCombatRegistryChecks.Run();
CombatInputChecks.Run();
StartLocationChecks.Run();
MapEntryChecks.Run();
MoogleP5GuideChecks.Run();
MoogleChecks.Run();
MoogleTimelineChecks.Run();
HelloWorldChecks.Run();
HelloWorldMechanicsChecks.Run();
TransitionChecks.Run();
TransitionScenarioChecks.Run();
Console.WriteLine("P3 regression checks passed.");
SigmaTowerChecks.Run();
DeltaSettingsChecks.Run();
BlueScreenChecks.Run();
NetChecks.Run();
MultiplayerChecks.Run();
